[package]
name = "dom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = {path="../macros"}
unicode-bidi = "0.3.13"
